/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e8e7f3",
        "secondary": "#505f76",
        "on-primary-fixed-variant": "#0039b5",
        "background": "#faf8ff",
        "on-tertiary-container": "#ffc9b7",
        "surface-variant": "#e2e1ed",
        "primary-container": "#1d4ed8",
        "on-surface": "#1a1b23",
        "on-background": "#1a1b23",
        "surface-container-low": "#f3f2fe",
        "primary-fixed-dim": "#b7c4ff",
        "on-surface-variant": "#434655",
        "on-primary-container": "#cad3ff",
        "on-secondary-fixed-variant": "#38485d",
        "primary-fixed": "#dce1ff",
        "on-secondary-container": "#54647a",
        "inverse-on-surface": "#f0f0fb",
        "surface-tint": "#2151da",
        "inverse-primary": "#b7c4ff",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-container": "#a73400",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "secondary-container": "#d0e1fb",
        "inverse-surface": "#2e3039",
        "surface-container-highest": "#e2e1ed",
        "on-tertiary-fixed-variant": "#832700",
        "on-error": "#ffffff",
        "surface-dim": "#d9d9e5",
        "outline-variant": "#c4c5d7",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#390c00",
        "on-secondary-fixed": "#0b1c30",
        "outline": "#747686",
        "on-primary": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-secondary": "#ffffff",
        "tertiary": "#7f2500",
        "surface": "#faf8ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#b7c8e1",
        "tertiary-fixed-dim": "#ffb59c",
        "primary": "#0037b0",
        "secondary-fixed": "#d3e4fe",
        "surface-container": "#ededf9",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001551"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "0.5rem",
        "base": "4px",
        "md": "1rem",
        "gutter": "1.5rem",
        "margin": "2rem",
        "lg": "1.5rem",
        "xl": "2rem",
        "xs": "0.25rem",
        "2xl": "3rem"
      }
    },
  },
  plugins: [],
}
